// BradtTaversy_Projects_Collection/18_vuex/src/components/AddTodo.vue
<template>
	<div>
		<h3>Add Todo</h3>
		<div class="add">
			<form @submit="onSubmit">
				<input type="text" v-model="title" placeholder="Add Todo..." />
				<input type="submit" value="Submit" />
			</form>
		</div>
	</div>
</template>

<script>
import { mapActions } from "vuex";
export default {
	name: "AddTodo",
	data() {
		return {
			title: ""
		};
	},
	methods: {
		...mapActions(["addTodo"]),
		onSubmit(e) {
			e.preventDefault();
			this.addTodo(this.title);
		}
	}
};
</script>

<style scoped>
form {
	display: flex;
}
input[type="text"] {
	flex: 10;
	padding: 10px;
	border: 1px solid #41b883;
	outline: 0;
}
input[type="submit"] {
	flex: 2;
	background: #41b883;
	color: #fff;
	border: 1px #41b883 solid;
	cursor: pointer;
}
</style>

// BradtTaversy_Projects_Collection/22_react-js-crash-course/src/components/todos/AddTodo.js
import React, { Component } from 'react'
import PropTypes from 'prop-types'

export class AddTodo extends Component {
  state = {
    title: '',
  }

  onChange = (e) => {
    return this.setState({
      [e.target.name]: e.target.value
    });
  }

  onSubmit = (e) => {
    e.preventDefault();
    this.props.addTodo(this.state.title);
    this.setState({
      title: '',
    });
  }

  render() {
    return (
      <form onSubmit={this.onSubmit} style={{ display: 'flex' }}>
        <input
          style={{flex: '10', padding: '5px'}}
          type="text"
          name="title"
          placeholder="Add Todo..."
          value={this.state.title}
          onChange={this.onChange}
        />

        <input
          type="submit"
          value="Submit"
          className="btn"
          style={{flex: '1'}}
        />
      </form>
    )
  }
}

// PropTypes
AddTodo.propType = {
  addTodo: PropTypes.func.isRequired,
 }

export default AddTodo
