// BradtTaversy_Projects_Collection/14_yt_vueJs/src/components/AddTodo.vue
<template>
  <div>
    <form @submit="addTodo">
      <input
        type="text"
        v-model="title"
        name="title"
        placeholder="Add todo here"
      >
      <input
        type="submit"
        value="Submit"
        class="btn"
      >
    </form>
  </div>
</template>

<script>
// import uuid from "uuid";
export default {
  name: "AddTodo",
  data() {
    return {
      title: ""
    };
  },
  methods: {
    addTodo(e) {
      e.preventDefault();
      const newTodo = {
        title: this.title,
        completed: false
      };
      // Send up to parent
      this.$emit("add-todo", newTodo);
      // Empty input field
      this.title = "";
    }
  }
};
</script>

<style scoped>
form {
  display: flex;
}
input[type="text"] {
  flex: 10;
  padding: 5px;
}
input[type="submit"] {
  flex: 2;
}
</style>

// BradtTaversy_Projects_Collection/22_react-js-crash-course/src/components/todos/AddTodo.js
import React, { Component } from 'react'
import PropTypes from 'prop-types'

export class AddTodo extends Component {
  state = {
    title: '',
  }

  onChange = (e) => {
    return this.setState({
      [e.target.name]: e.target.value
    });
  }

  onSubmit = (e) => {
    e.preventDefault();
    this.props.addTodo(this.state.title);
    this.setState({
      title: '',
    });
  }

  render() {
    return (
      <form onSubmit={this.onSubmit} style={{ display: 'flex' }}>
        <input
          style={{flex: '10', padding: '5px'}}
          type="text"
          name="title"
          placeholder="Add Todo..."
          value={this.state.title}
          onChange={this.onChange}
        />

        <input
          type="submit"
          value="Submit"
          className="btn"
          style={{flex: '1'}}
        />
      </form>
    )
  }
}

// PropTypes
AddTodo.propType = {
  addTodo: PropTypes.func.isRequired,
 }

export default AddTodo
