// BradtTaversy_Projects_Collection/14_yt_vueJs/src/components/Todos.vue
<template>
  <div>
    <div
      v-bind:key="todo.id"
      v-for="todo in todos"
    >
      <TodoItem
        v-bind:todo="todo"
        v-on:del-todo="$emit('del-todo', todo.id)"
      >
      </TodoItem>
    </div>
  </div>
</template>

<script>
import TodoItem from "./TodoItem.vue";

export default {
  name: "Todos",
  components: {
    TodoItem
  },
  props: ["todos"]
};
</script>


<style scoped>
</style>

// React_The_Complete_Guide/typescript-wt-react/src/components/Todos.tsx
import React from "react"
import Todo from "../models/todo"
import TodoItem from "./TodoItem"
import classes from "./Todos.module.css"

const Todos: React.FC<{ items: Todo[]; onRemoveTodo: (id: string) => void }> = (props) => {
  return (
    <ul className={classes.todos}>
      {props.items.map((item) => (
        <TodoItem key={item.id} text={item.text} onRemoveTodo={props.onRemoveTodo.bind(null, item.id)} />
      ))}
    </ul>
  )
}

export default Todos
