// BradtTaversy_Projects_Collection/22_react-js-crash-course/src/components/todos/TodoItem.js
import React, { Component } from 'react'
import PropTypes from 'prop-types';

export class TodoItem extends Component {
  getStyle = () => {
    return {
      textDecoration:  this.props.todo.completed ? 'line-through' : 'none',
      borderBottom: '1px #ccc dotted',
      backgroundColor: '#f4f4f4',
      padding: '10px',
    }
  }

  render() {
    const { id, title } = this.props.todo;
    return (
      <div style={this.getStyle()}>
        <p>
          <input type="checkbox" onChange={this.props.toggleComplete.bind(this,id)} /> {' '}
          { title }
          <button onClick={this.props.delTodo.bind(this, id)} style={btnStyle}>X</button>
        </p>
      </div>
    )
  }
}

// PropTypes
TodoItem.propType = {
  todos: PropTypes.array.isRequired,
  toggleComplete: PropTypes.func.isRequired,
  delTodo: PropTypes.func.func,
 }

const btnStyle = {
  borderRadius: '50%',
  padding: '5px 9px',
  background: '#ff0000',
  cursor: 'pointer',
  color: '#fff',
  border: 'none',
  float: 'right',
}

export default TodoItem

// BradtTaversy_Projects_Collection/14_yt_vueJs/src/components/TodoItem.vue
<template>
  <div
    class="todo-item"
    v-bind:class="{'is-complete':todo.completed}"
  >
    <button
      @click="$emit('del-todo', todo.id)"
      class="del"
    >x</button>
    <p>
      <input
        type="checkbox"
        v-on:change="markComplete"
      >
      {{todo.title}}</p>
  </div>
</template>

<script>
export default {
  name: "todoItem",
  props: ["todo"],
  methods: {
    markComplete() {
      this.todo.completed = !this.todo.completed;
    }
  }
};
</script>

<style scoped>
.todo-item {
  background: #f4f4f4;
  padding: 10px;
  border-bottom: 1px #ccc dotted;
}
.is-complete {
  text-decoration: line-through;
}
.del {
  background: #ff0000;
  color: #fff;
  border: none;
  padding: 5px 9px;
  border-radius: 50%;
  cursor: pointer;
  float: right;
}
</style>
